export const scoreOfficial = {
    "mex-za": { home: 2, away: 0, finished: true },
    "kr-cz": { home: 2, away: 1, finished: true },
    "ca-ba": { home: 1, away: 1, finished: true },
    "us-py": { home: 4, away: 1, finished: true },
    "qa-ch": { home: 1, away: 1, finished: true },
    "br-ma": { home: 1, away: 1, finished: true },
    "ht-sct": { home: 0, away: 1, finished: true },
    "au-tr": { home: 2, away: 0, finished: true },
    "de-cw": { home: 7, away: 1, finished: true },
    "nl-jp": { home: 2, away: 2, finished: true },

    "ci-ec": { home: 0, away: 0, finished: false },
    "se-tn": { home: 0, away: 0, finished: false },
    "es-cv": { home: 0, away: 0, finished: false },
    "be-eg": { home: 0, away: 0, finished: false },
    "sa-uy": { home: 0, away: 0, finished: false },
    "ir-nz": { home: 0, away: 0, finished: false },
    "fr-sn": { home: 0, away: 0, finished: false },
    "iq-no": { home: 0, away: 0, finished: false },
    "ar-dz": { home: 0, away: 0, finished: false },
    "at-jo": { home: 0, away: 0, finished: false },

    "pt-cd": { home: 0, away: 0, finished: false },
    "eng-hr": { home: 0, away: 0, finished: false },
    "gh-pa": { home: 0, away: 0, finished: false },
    "uz-co": { home: 0, away: 0, finished: false },

    "cz-za": { home: 0, away: 0, finished: false },
    "ch-ba": { home: 0, away: 0, finished: false },
    "ca-qa": { home: 0, away: 0, finished: false },
    "mx-kr": { home: 0, away: 0, finished: false },
    "us-au": { home: 0, away: 0, finished: false },
    "sct-ma": { home: 0, away: 0, finished: false },
    "br-ht": { home: 0, away: 0, finished: false },
    "tr-py": { home: 0, away: 0, finished: false },
    "nl-se": { home: 0, away: 0, finished: false },
    "de-ci": { home: 0, away: 0, finished: false },

    "ec-cw": { home: 0, away: 0, finished: false },
    "tn-jp": { home: 0, away: 0, finished: false },
    "es-sa": { home: 0, away: 0, finished: false },
    "be-ir": { home: 0, away: 0, finished: false },
    "uy-cv": { home: 0, away: 0, finished: false },
    "nz-eg": { home: 0, away: 0, finished: false },
    "ar-at": { home: 0, away: 0, finished: false },
    "fr-iq": { home: 0, away: 0, finished: false },
    "no-sn": { home: 0, away: 0, finished: false },
    "jo-dz": { home: 0, away: 0, finished: false },

    "pt-uz": { home: 0, away: 0, finished: false },
    "eng-gh": { home: 0, away: 0, finished: false },
    "pa-hr": { home: 0, away: 0, finished: false },
    "co-cd": { home: 0, away: 0, finished: false },
    "ch-ca": { home: 0, away: 0, finished: false },
    "ba-qa": { home: 0, away: 0, finished: false },
    "ma-ht": { home: 0, away: 0, finished: false },
    "sct-br": { home: 0, away: 0, finished: false },
    "za-kr": { home: 0, away: 0, finished: false },
    "cz-mx": { home: 0, away: 0, finished: false },

    "cw-ci": { home: 0, away: 0, finished: false },
    "ec-de": { home: 0, away: 0, finished: false },
    "tn-nl": { home: 0, away: 0, finished: false },
    "jp-se": { home: 0, away: 0, finished: false },
    "tr-us": { home: 0, away: 0, finished: false },
    "py-au": { home: 0, away: 0, finished: false },
    "no-fr": { home: 0, away: 0, finished: false },
    "sn-iq": { home: 0, away: 0, finished: false },
    "cv-sa": { home: 0, away: 0, finished: false },
    "uy-es": { home: 0, away: 0, finished: false },

    "nz-be": { home: 0, away: 0, finished: false },
    "eg-ir": { home: 0, away: 0, finished: false },
    "pa-eng": { home: 0, away: 0, finished: false },
    "hr-gh": { home: 0, away: 0, finished: false },
    "co-pt": { home: 0, away: 0, finished: false },
    "cd-uz": { home: 0, away: 0, finished: false },
    "dz-at": { home: 0, away: 0, finished: false },
    "jo-ar": { home: 0, away: 0, finished: false }
};
